"""initial_schema

Revision ID: da5b181d8676
Revises: 
Create Date: 2026-06-25 10:53:58.183303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da5b181d8676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('admin', 'supervisor', 'atendente', name='perfilatendente'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendente_email'), 'atendente', ['email'], unique=True)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('versao_erp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_documento'), 'cliente', ['documento'], unique=True)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('fiscal', 'estoque', 'compras', 'vendas', 'financeiro', name='categoriaconhecimento'), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=50), nullable=True),
    sa.Column('url_arquivo', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('novo', 'ia_analisando', 'aguardando_cliente', 'aguardando_humano_com_solucao', 'aguardando_humano_sem_solucao', 'em_atendimento', 'resolvido', 'encerrado', name='statuschat'), nullable=False),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', 'urgente', name='prioridadechat'), nullable=False),
    sa.Column('resumo_problema', sa.Text(), nullable=True),
    sa.Column('solucao_sugerida_ia', sa.Text(), nullable=True),
    sa.Column('causa_provavel', sa.Text(), nullable=True),
    sa.Column('nivel_confianca_ia', sa.Float(), nullable=True),
    sa.Column('necessita_humano', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('ultima_mensagem_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendente.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_cliente_id'), 'chat', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    op.create_table('chat_tag',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'tag_id')
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('alterado_por', sa.String(length=255), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_chat_id'), 'historico', ['chat_id'], unique=False)
    op.create_table('ia_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('status_ia', sa.Enum('resolvido_pela_ia', 'transferir_com_solucao', 'transferir_sem_solucao', name='statusia'), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('causa_provavel', sa.Text(), nullable=True),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_diagnostico_chat_id'), 'ia_diagnostico', ['chat_id'], unique=False)
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.Enum('cliente', 'ia', 'atendente', 'sistema', name='remetentemensagem'), nullable=False),
    sa.Column('tipo', sa.Enum('texto', 'audio', 'documento', 'imagem', name='tipomensagem'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('url_arquivo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_chat_id'), 'mensagem', ['chat_id'], unique=False)
    op.create_index(op.f('ix_mensagem_created_at'), 'mensagem', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagem_created_at'), table_name='mensagem')
    op.drop_index(op.f('ix_mensagem_chat_id'), table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_index(op.f('ix_ia_diagnostico_chat_id'), table_name='ia_diagnostico')
    op.drop_table('ia_diagnostico')
    op.drop_index(op.f('ix_historico_chat_id'), table_name='historico')
    op.drop_table('historico')
    op.drop_table('chat_tag')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_cliente_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_table('loja')
    op.drop_table('tag')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_cliente_documento'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_atendente_email'), table_name='atendente')
    op.drop_table('atendente')
    # ### end Alembic commands ###
