"""remove_historico_table

Revision ID: ec53387401ba
Revises: da5b181d8676
Create Date: 2026-06-25 13:10:11.751207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec53387401ba'
down_revision: Union[str, None] = 'da5b181d8676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_chat_id'), table_name='historico')
    op.drop_table('historico')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('campo_alterado', sa.VARCHAR(length=100), nullable=False),
    sa.Column('valor_anterior', sa.TEXT(), nullable=True),
    sa.Column('valor_novo', sa.TEXT(), nullable=True),
    sa.Column('alterado_por', sa.VARCHAR(length=255), nullable=False),
    sa.Column('alterado_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_chat_id'), 'historico', ['chat_id'], unique=False)
    # ### end Alembic commands ###
